ALTER TABLE endpoints ADD COLUMN is_root INTEGER NOT NULL DEFAULT 1;
ALTER TABLE tasks ADD COLUMN is_root INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_traces ADD COLUMN is_root INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_traces ADD COLUMN distributed_trace_id TEXT DEFAULT NULL;
