#!/usr/bin/env bash
set -euo pipefail

# Backfill GitHub Releases for existing backend/v* tags.
# Skips any tag that already has a release.
# Notes are auto-generated by GitHub from commits since the previous tag.
#
# Requirements: gh CLI authenticated (`gh auth status`).
# Usage: scripts/backfill-github-releases.sh [--dry-run]

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI not found" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "error: gh CLI not authenticated. Run: gh auth login" >&2
  exit 1
fi

mapfile -t TAGS < <(git tag --list 'backend/v*' --sort=version:refname)

if [[ ${#TAGS[@]} -eq 0 ]]; then
  echo "no backend/v* tags found"
  exit 0
fi

PREV_TAG=""
for TAG in "${TAGS[@]}"; do
  VERSION="${TAG#backend/v}"
  TITLE="Backend v${VERSION}"

  if gh release view "$TAG" >/dev/null 2>&1; then
    echo "skip ${TAG} (release already exists)"
    PREV_TAG="$TAG"
    continue
  fi

  echo "create ${TAG} -> '${TITLE}'"

  if [[ $DRY_RUN -eq 1 ]]; then
    PREV_TAG="$TAG"
    continue
  fi

  ARGS=(release create "$TAG" --title "$TITLE" --generate-notes)
  if [[ -n "$PREV_TAG" ]]; then
    ARGS+=(--notes-start-tag "$PREV_TAG")
  fi

  gh "${ARGS[@]}"
  PREV_TAG="$TAG"
done

echo "done."
